# General Configuration
packetbeat.interfaces.device: any
packetbeat.interfaces.type: af_packet
packetbeat.interfaces.buffer_size_mb: 100

# Inputs
packetbeat.flows:
  timeout: 30s
  period: 10s

packetbeat.protocols:
- type: icmp
  enabled: true
- type: dhcpv4
  ports: [67, 68]
- type: dns
  ports: [53]
- type: http
  ports: [80, 8080, 8000, 5000, 8002]
- type: amqp
  ports: [5672]
- type: cassandra
  ports: [9042]
- type: memcache
  ports: [11211]
- type: mysql
  ports: [3306,3307]
- type: redis
  ports: [6379]
- type: pgsql
  ports: [5432]
- type: thrift
  ports: [9090]
- type: tls
  ports: [443, 993, 995, 5223, 8443, 8883, 9243]

# Processors
processors:
  - add_host_metadata: ~

# Kibana Instance
setup.kibana:
  hosts: ["127.0.0.1:5601"]
  username: "elastic"
  password: "changeme"

# Logtash Instance
output.elasticsearch:
  hosts: ["127.0.0.1:9200"]
  username: "elastic"
  password: "changeme"
